# Automatically approve workflow runs from first time contributors.
# This action will be run on a schedule within the organisation.
# See https://github.com/mheap/automatic-approve-action

name: approve-workflow

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch: {}

jobs:
  auto-approve:
    name: auto-approve
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve
        uses: mheap/automatic-approve-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflows: "ci.yml,code-check.yml,license.yml"
          dangerous_files: ".github/workflows"
