name: CI-Pipeline

on:
  push:
    branches:
      - master
      - release-*
      - feature-*
  pull_request:
    branches:
      - master
      - release-*
      - feature-*
  workflow_dispatch: {}

env:
  GO_VERSION: 1.16

jobs:
  # Run this job will skip duplicate actions
  detect-duplicate:
    name: detect-duplicate
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Detect Duplicate
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          concurrent_skipping: false
          paths_ignore: '["**/docs/**", "**.md", "**.mdx", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
  build:
    name: compile
    needs: detect-duplicate
    runs-on: ubuntu-latest
    if: needs.detect-duplicate.outputs.should_skip != 'true' 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Compile
        run: go build -o bin/openwald cmd/openwald/main.go

  ut-test:
    name: ut-test
    needs: [detect-duplicate, build]
    runs-on: ubuntu-latest
    if: needs.detect-duplicate.outputs.should_skip != 'true' 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run ut-test
        run: bash hack/test/run_ut.sh

  e2e-test:
    name: e2e-test
    needs: [detect-duplicate, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run e2e-test 
        run: bash hack/test/run_e2e.sh
