name: Code-Check

on:
  push:
  pull_request:

jobs:
  # Run this job will skip duplicate actions
  detect-noop:
    name: detect-noop
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Detect Noop
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          concurrent_skipping: false
          paths_ignore: '["**/docs/**", "**.md", "**.mdx", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'

  golangci-lint:
    name: golangci-lint
    needs: detect-noop
    runs-on: ubuntu-latest
    if: needs.detect-noop.outputs.should_skip != 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
