name: Code-Check

on:
  push:
    branches:
      - master
      - release-*
      - feature-*
  pull_request:
    branches:
      - master
      - release-*
      - feature-*
  workflow_dispatch: {}

env:
  GO_VERSION: 1.16

jobs:
  # Run this job will skip duplicate actions
  detect-duplicate:
    name: detect-duplicate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Detect Duplicate
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          concurrent_skipping: false
          paths_ignore: '["**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
  
  # Go linters
  golangci-lint:
    name: golangci-lint
    needs: detect-duplicate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: needs.detect-duplicate.outputs.should_skip != 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2

  # Check misspellings
  codespell:
    name: codespell
    needs: detect-duplicate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: needs.detect-duplicate.outputs.should_skip != 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run codespell
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          # When using this Action in other repos, the --skip option below can be removed
          # Comma-separated list of list
          skip: .git
          ignore_words_file: .github/config/codespell/.codespellignore

  # Check tab
  check-tab:
    name: check-tab
    needs: detect-duplicate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: needs.detect-duplicate.outputs.should_skip != 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run check-tab
        run: bash hack/codecheck/check_tab.sh
