name: Code-Check

on:
  push:
  pull_request:

jobs:
  # Run this job will skip duplicate actions
  detect-duplicate:
    name: detect-duplicate
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Detect Duplicate
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          concurrent_skipping: false
          paths_ignore: '["**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
  
  # Go linters
  golangci-lint:
    name: golangci-lint
    needs: detect-duplicate
    runs-on: ubuntu-latest
    if: needs.detect-duplicate.outputs.should_skip != 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2

  # Check misspellings
  codespell:
    name: codespell
    needs: detect-duplicate
    runs-on: ubuntu-latest
    if: needs.detect-duplicate.outputs.should_skip != 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run codespell
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          # When using this Action in other repos, the --skip option below can be removed
          # Comma-separated list of list
          skip: .git
          ignore_words_file: .github/config/codespell/.codespellignore

  # Check tab
  check-tab:
    name: check-tab
    needs: detect-duplicate
    runs-on: ubuntu-latest
    if: needs.detect-duplicate.outputs.should_skip != 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run check-tab
        run: bash hack/codecheck/check_tab.sh

  #codespell:
  #  name: codespell
  #  needs: detect-duplicate
  #  runs-on: ubuntu-latest
  #  if: needs.detect-duplicate.outputs.should_skip != 'true'
  #  steps:
  #    - name: Checkout Code
  #      uses: actions/checkout@v3
  #    - name: Setup Python
  #      uses: actions/setup-python@v3
  #      with:
  #        python-version: 3.9
  #        architecture: x64
  #    - name: Install codespell
  #      run: pip install codespell==2.1.0
  #    - name: Run codespell
  #      run: bash hack/codecheck/check_codespell.sh
