name: image-latest

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master

env:
  GO_VERSION: 1.16
  IMAGE_TAG: latest

jobs:
  publish-dockerhub:
    name: publish-dockerhub
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Images
        run: |
          CGO_ENABLED=0 GOOS=$(go env GOOS) go build -o bin/openwald cmd/openwald/main.go 
          docker buildx build --push --platform="linux/amd64,linux/arm64" --tag="openwald/openwald:${{ env.IMAGE_TAG }}" --file=docker/Dockerfile .

  publish-swr:
    name: publish-swr
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    env:
      SWR_REGION: cn-east-3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login Huaweicloud-SWR
        uses: huaweicloud/swr-login@v1
        with:
          region: ${{ env.SWR_REGION }}
          access-key-id: ${{ secrets.SWR_AK }}
          access-key-secret: ${{ secrets.SWR_SK }}
      - name: Push Images
        run: |
          CGO_ENABLED=0 GOOS=$(go env GOOS) go build -o bin/openwald cmd/openwald/main.go 
          docker buildx build --push --platform="linux/amd64" --tag="swr.${{ env.SWR_REGION }}.myhuaweicloud.com/openwald/openwald:${{ env.IMAGE_TAG }}" --file=docker/Dockerfile .
