name: release-image-swr

on:
  release:
    types:
      - published

jobs:
  publish-image:
    name: publish-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login Huaweicloud-SWR
        uses: huaweicloud/swr-login@v1
        with:
          region: cn-east-3 
          access-key-id: ${{ secrets.SWR_AK }}
          access-key-secret: ${{ secrets.SWR_SK }}
      - name: Publish Images
        run: |
          CGO_ENABLED=0 GOOS=$(go env GOOS) go build -o bin/openwald cmd/openwald/main.go 
          docker buildx build --push --platform="linux/amd64,linux/arm64" --tag="openwald/openwald:latest" --file=docker/Dockerfile .
