name: License

on:
  push:
    branchs:
      - master
      - release-*
      - feature-*
  pull_request:
      - master
      - release-*
      - feature-*
  workflow_dispatch: {}

env:
  RUBY_VERSION: 2.6

jobs:
  # Run this job will skip duplicate actions
  detect-duplicate:
    name: detect-duplicate
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Detect Duplicate
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          concurrent_skipping: false
          paths_ignore: '["**/docs/**", "**.md", "**.mdx", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
  
  # Detect the licenses of the packages
  license-finder:
    name: license-finder
    needs: detect-duplicate
    runs-on: ubuntu-latest
    if: needs.detect-duplicate.outputs.should_skip != 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install license_finder
        run: gem install license_finder -v 7.0.1
      - name: Run license_finder
        run: license_finder --decisions_file .github/config/license_finder/dependency_decisions.yml
  
  # Check license header
  check-license-header:
    name: check-license-header
    needs: detect-duplicate
    runs-on: ubuntu-latest
    if: needs.detect-duplicate.outputs.should_skip != 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Check License Header
        uses: apache/skywalking-eyes@v0.2.0
        with:
          log: info
          config: .github/config/license_header/.licenserc.yml

  # Check copyright
  check-copyright:
    name: check-copyright
    needs: detect-duplicate
    runs-on: ubuntu-latest
    if: needs.detect-duplicate.outputs.should_skip != 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run check-copyright
        run: bash hack/codecheck/check_copyright.sh
